import { BeadColor } from './types';

// A subset of popular Perler colors
export const PERLER_COLORS: BeadColor[] = [
  { id: 'P01', brand: 'Perler', name: 'White', hex: '#FFFFFF' },
  { id: 'P02', brand: 'Perler', name: 'Cream', hex: '#EBE1C4' },
  { id: 'P03', brand: 'Perler', name: 'Yellow', hex: '#F2CD22' },
  { id: 'P04', brand: 'Perler', name: 'Orange', hex: '#F05D22' },
  { id: 'P05', brand: 'Perler', name: 'Red', hex: '#C62928' },
  { id: 'P06', brand: 'Perler', name: 'Bubblegum', hex: '#E65682' },
  { id: 'P07', brand: 'Perler', name: 'Purple', hex: '#774C97' },
  { id: 'P08', brand: 'Perler', name: 'Dark Blue', hex: '#1C2B59' },
  { id: 'P09', brand: 'Perler', name: 'Light Blue', hex: '#3776A8' },
  { id: 'P10', brand: 'Perler', name: 'Green', hex: '#347242' },
  { id: 'P11', brand: 'Perler', name: 'Light Green', hex: '#97CC65' },
  { id: 'P12', brand: 'Perler', name: 'Brown', hex: '#523428' },
  { id: 'P13', brand: 'Perler', name: 'Grey', hex: '#8C9094' },
  { id: 'P14', brand: 'Perler', name: 'Black', hex: '#1C1C1E' }, // Adjusted black to not be pure 000
  { id: 'P17', brand: 'Perler', name: 'Clear', hex: '#D2D8D6' },
  { id: 'P18', brand: 'Perler', name: 'Prickly Pear', hex: '#B8D563' },
  { id: 'P19', brand: 'Perler', name: 'Sand', hex: '#D7BC97' },
  { id: 'P20', brand: 'Perler', name: 'Rust', hex: '#9C372A' },
  { id: 'P21', brand: 'Perler', name: 'Light Brown', hex: '#946643' },
  { id: 'P22', brand: 'Perler', name: 'Peach', hex: '#F2C8A4' },
  { id: 'P23', brand: 'Perler', name: 'Tan', hex: '#C29C7C' },
  { id: 'P26', brand: 'Perler', name: 'Pastel Lavender', hex: '#967BB6' },
  { id: 'P27', brand: 'Perler', name: 'Pastel Yellow', hex: '#FDF383' },
  { id: 'P28', brand: 'Perler', name: 'Pastel Green', hex: '#87D397' },
  { id: 'P30', brand: 'Perler', name: 'Butterscotch', hex: '#D89E46' },
  { id: 'P31', brand: 'Perler', name: 'Turquoise', hex: '#008390' },
  { id: 'P33', brand: 'Perler', name: 'Glow in Dark', hex: '#E8EAD3' },
  { id: 'P35', brand: 'Perler', name: 'Neon Green', hex: '#53AF3C' },
  { id: 'P36', brand: 'Perler', name: 'Neon Pink', hex: '#FF007F' },
  { id: 'P38', brand: 'Perler', name: 'Neon Orange', hex: '#FF6F00' },
  { id: 'P39', brand: 'Perler', name: 'Neon Yellow', hex: '#F0F032' },
  { id: 'P47', brand: 'Perler', name: 'Plum', hex: '#953457' },
  { id: 'P48', brand: 'Perler', name: 'Toasted Marshmallow', hex: '#E1D3C6' },
  { id: 'P49', brand: 'Perler', name: 'Spruce', hex: '#375751' },
  { id: 'P51', brand: 'Perler', name: 'Cranapple', hex: '#8F2633' },
  { id: 'P52', brand: 'Perler', name: 'Kiwi Lime', hex: '#7AC943' },
  { id: 'P58', brand: 'Perler', name: 'Toothpaste', hex: '#94D0D2' },
  { id: 'P59', brand: 'Perler', name: 'Hot Coral', hex: '#FF5A5F' },
  { id: 'P60', brand: 'Perler', name: 'Plum', hex: '#822754' },
  { id: 'P61', brand: 'Perler', name: 'Fern', hex: '#395E35' },
  { id: 'P70', brand: 'Perler', name: 'Apricot', hex: '#FBB978' },
  { id: 'P79', brand: 'Perler', name: 'Lagoon', hex: '#006B91' },
  { id: 'P80', brand: 'Perler', name: 'Midnight', hex: '#0F1E38' },
  { id: 'P82', brand: 'Perler', name: 'Shamrock', hex: '#007C41' },
  { id: 'P83', brand: 'Perler', name: 'Cobalt', hex: '#0058A8' },
  { id: 'P85', brand: 'Perler', name: 'Eggplant', hex: '#3E2548' },
  { id: 'P88', brand: 'Perler', name: 'Cherry', hex: '#A81C30' },
  { id: 'P91', brand: 'Perler', name: 'Silver', hex: '#9EA3A8' },
  { id: 'P92', brand: 'Perler', name: 'Gold', hex: '#AC8A42' },
];

export const TRANSLATIONS = {
  en: {
    appTitle: "PixelCraft",
    upload: "Upload Image",
    width: "Width (beads)",
    grid: "Show Grid",
    numbers: "Show IDs",
    palette: "Palette",
    managePalette: "Manage Palette",
    stats: "BOM (Bill of Materials)",
    totalBeads: "Total Beads",
    download: "Export Pattern",
    emptyState: "Upload an image to start crafting.",
    dragDrop: "Drag & drop an image here",
    settings: "Settings",
    owned: "Owned",
    missing: "Missing",
    searchColor: "Search color...",
    processing: "Processing...",
    close: "Close",
    selectAll: "Select All",
    deselectAll: "Deselect All",
  },
  zh: {
    appTitle: "拼豆工坊",
    upload: "上传图片",
    width: "宽度 (像素)",
    grid: "显示网格",
    numbers: "显示色号",
    palette: "色板管理",
    managePalette: "管理详细色板",
    stats: "用量统计",
    totalBeads: "总计珠子",
    download: "导出图纸",
    emptyState: "请上传图片开始制作。",
    dragDrop: "拖拽图片到此处",
    settings: "设置",
    owned: "已拥有",
    missing: "未拥有",
    searchColor: "搜索颜色...",
    processing: "处理中...",
    close: "关闭",
    selectAll: "全选",
    deselectAll: "取消全选",
  }
};